# Generated by Django 5.1.4 on 2024-12-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_digital_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
